services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: devsecops-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_data:
