apiVersion: v1
kind: Service
metadata:
  name: my-app-service-active
spec:
  type: LoadBalancer
  selector:
    app: my-app
    color: ACTIVE_COLOR
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
